app/main/default/objects/Flosum__Patch_Manifest__c/fields/Flosum__Patch__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Flosum__Patch__c</fullName>
        <label>Deployment</label>
        <referenceTo>Flosum__Patch__c</referenceTo>
        <relationshipLabel>Deployment Manifests</relationshipLabel>
        <relationshipName>Patch_Manifests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

app/main/default/classes/ChangedByUserController.cls
public class ChangedByUserController {
	@AuraEnabled
	public static String getDetails(Id recordId) {
        Map<String,Integer> detailMap = new Map<String,Integer>();
        List<AggregateResult> patchApp = [Select count(id),Flosum__Developer__c From Flosum__Patch_Manifest__c where Flosum__Patch__c =: recordId Group By Flosum__Developer__c ];
        for(AggregateResult agg : patchApp){
            String userName = String.valueOf(agg.get('Flosum__Developer__c'));
            Integer deploymentCount = Integer.valueOf(agg.get('expr0'));
            detailMap.put(userName,deploymentCount);
        }
        System.debug(detailMap);
        string detailString = JSON.serialize(detailMap);
        System.debug(detailString);
   		return detailString;
	}
}